import { NextResponse } from "next/server";
import { upsertProperty } from "@/lib/firestore";
import type { Property } from "@/types/property";

const SEED_PROPERTIES: Property[] = [
  {
    id: "rightmove_seed_1",
    currentPrice: 1800,
    originalPrice: 2200,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-1.jpg",
    estateAgent: "Foxtons",
    address: "42 Baker Street, Marylebone, London W1U 3BW",
    postcode: "W1U 3BW",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-1",
    city: "London",
    dateListed: "2026-01-15T10:00:00Z",
    furnished: true,
    bedrooms: 2,
    description:
      "Stunning two-bedroom flat in the heart of Marylebone. Recently refurbished with modern fittings throughout. Walking distance to Baker Street station.",
    type: "Flat",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_2",
    currentPrice: 3500,
    originalPrice: 4200,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-2.jpg",
    estateAgent: "Knight Frank",
    address: "15 Chelsea Embankment, Chelsea, London SW3 4LB",
    postcode: "SW3 4LB",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-2",
    city: "London",
    dateListed: "2025-12-01T09:00:00Z",
    furnished: true,
    bedrooms: 3,
    description:
      "Magnificent three-bedroom apartment overlooking the Thames. Features include a private balcony, concierge service, and underground parking.",
    type: "Flat",
    createdAt: "2025-12-01T09:00:00Z",
    updatedAt: "2026-02-28T14:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_3",
    currentPrice: 1200,
    originalPrice: 1350,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-3.jpg",
    estateAgent: "Hamptons",
    address: "88 Brick Lane, Shoreditch, London E1 6RL",
    postcode: "E1 6RL",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-3",
    city: "London",
    dateListed: "2026-02-10T11:00:00Z",
    furnished: false,
    bedrooms: 1,
    description:
      "Charming one-bedroom flat in trendy Shoreditch. Exposed brick walls, wooden floors, and plenty of natural light. Close to vibrant nightlife and restaurants.",
    type: "Flat",
    createdAt: "2026-02-10T11:00:00Z",
    updatedAt: "2026-03-05T09:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_4",
    currentPrice: 2800,
    originalPrice: 2800,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-4.jpg",
    estateAgent: "Savills",
    address: "7 Kensington Palace Gardens, London W8 4QP",
    postcode: "W8 4QP",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-4",
    city: "London",
    dateListed: "2026-03-01T08:00:00Z",
    furnished: true,
    bedrooms: 2,
    description:
      "Elegant two-bedroom apartment in a prestigious Kensington address. Period features combined with contemporary living. Access to private communal gardens.",
    type: "Flat",
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-03-01T08:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_5",
    currentPrice: 950,
    originalPrice: 1100,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-5.jpg",
    estateAgent: "Winkworth",
    address: "23 Camden High Street, Camden, London NW1 7JE",
    postcode: "NW1 7JE",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-5",
    city: "London",
    dateListed: "2026-01-20T15:00:00Z",
    furnished: null,
    bedrooms: 1,
    description:
      "Cozy studio flat above shops in bustling Camden. Ideal for young professionals. Minutes from Camden Town tube station.",
    type: "Studio",
    createdAt: "2026-01-20T15:00:00Z",
    updatedAt: "2026-03-04T10:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_6",
    currentPrice: 4500,
    originalPrice: 5800,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-6.jpg",
    estateAgent: "Strutt & Parker",
    address: "1 Canary Wharf, Isle of Dogs, London E14 5AB",
    postcode: "E14 5AB",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-6",
    city: "London",
    dateListed: "2025-11-15T09:00:00Z",
    furnished: true,
    bedrooms: 3,
    description:
      "Luxury penthouse with panoramic views of Canary Wharf. Three bedrooms, two bathrooms, open-plan kitchen, and a wraparound terrace. 24-hour concierge.",
    type: "Flat",
    createdAt: "2025-11-15T09:00:00Z",
    updatedAt: "2026-03-02T16:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_7",
    currentPrice: 2100,
    originalPrice: 2500,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-7.jpg",
    estateAgent: "Chestertons",
    address: "56 Notting Hill Gate, London W11 3HT",
    postcode: "W11 3HT",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-7",
    city: "London",
    dateListed: "2026-01-05T12:00:00Z",
    furnished: true,
    bedrooms: 2,
    description:
      "Beautiful two-bedroom maisonette in Notting Hill. Spread over two floors with a private entrance, patio garden, and period features throughout.",
    type: "Maisonette",
    createdAt: "2026-01-05T12:00:00Z",
    updatedAt: "2026-03-03T11:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_8",
    currentPrice: 1650,
    originalPrice: 1650,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-8.jpg",
    estateAgent: "Marsh & Parsons",
    address: "12 Greenwich High Road, Greenwich, London SE10 8JL",
    postcode: "SE10 8JL",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-8",
    city: "London",
    dateListed: "2026-03-05T14:00:00Z",
    furnished: false,
    bedrooms: 2,
    description:
      "Spacious two-bedroom terraced house in historic Greenwich. Close to the park, maritime museum, and the Cutty Sark. Unfurnished with a private rear garden.",
    type: "Terraced",
    createdAt: "2026-03-05T14:00:00Z",
    updatedAt: "2026-03-05T14:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_9",
    currentPrice: 6000,
    originalPrice: 7500,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-9.jpg",
    estateAgent: "Harrods Estates",
    address: "3 Eaton Square, Belgravia, London SW1W 9DD",
    postcode: "SW1W 9DD",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-9",
    city: "London",
    dateListed: "2025-10-20T10:00:00Z",
    furnished: true,
    bedrooms: 4,
    description:
      "Exceptional four-bedroom apartment in one of London's most exclusive addresses. Grand reception rooms, staff quarters, and access to private garden square.",
    type: "Flat",
    createdAt: "2025-10-20T10:00:00Z",
    updatedAt: "2026-02-15T09:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_10",
    currentPrice: 1450,
    originalPrice: 1600,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-10.jpg",
    estateAgent: "Dexters",
    address: "91 Brixton Road, Brixton, London SW9 6LH",
    postcode: "SW9 6LH",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-10",
    city: "London",
    dateListed: "2026-02-01T13:00:00Z",
    furnished: true,
    bedrooms: 2,
    description:
      "Modern two-bedroom flat in vibrant Brixton. Open-plan living area, fully fitted kitchen, and balcony overlooking the high street. Close to Brixton Village.",
    type: "Flat",
    createdAt: "2026-02-01T13:00:00Z",
    updatedAt: "2026-03-06T10:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_11",
    currentPrice: 2200,
    originalPrice: 2200,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-11.jpg",
    estateAgent: "John D Wood",
    address: "45 Fulham Road, Fulham, London SW6 1EE",
    postcode: "SW6 1EE",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-11",
    city: "London",
    dateListed: "2026-03-07T09:00:00Z",
    furnished: false,
    bedrooms: 2,
    description:
      "Newly refurbished two-bedroom flat in a Victorian conversion. High ceilings, wooden floors, and a modern kitchen. Five minutes from Fulham Broadway station.",
    type: "Flat",
    createdAt: "2026-03-07T09:00:00Z",
    updatedAt: "2026-03-07T09:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
  {
    id: "rightmove_seed_12",
    currentPrice: 3200,
    originalPrice: 3800,
    imageUrl: "https://media.rightmove.co.uk/placeholders/property-12.jpg",
    estateAgent: "Benham and Reeves",
    address: "17 Tower Bridge Road, Southwark, London SE1 2UP",
    postcode: "SE1 2UP",
    externalUrl: "https://www.rightmove.co.uk/properties/seed-12",
    city: "London",
    dateListed: "2025-12-10T10:00:00Z",
    furnished: true,
    bedrooms: 3,
    description:
      "Impressive three-bedroom duplex with views of Tower Bridge. Features include a private roof terrace, floor-to-ceiling windows, and underfloor heating throughout.",
    type: "Flat",
    createdAt: "2025-12-10T10:00:00Z",
    updatedAt: "2026-03-01T15:00:00Z",
    supplier: "rightmove",
    urlSource: "https://www.rightmove.co.uk/property-to-rent/find.html",
  },
];

export async function POST() {
  try {
    let seeded = 0;
    for (const property of SEED_PROPERTIES) {
      await upsertProperty(property);
      seeded++;
    }

    return NextResponse.json({
      message: `Seeded ${seeded} properties`,
      seeded,
    });
  } catch (error) {
    console.error("Error seeding properties:", error);
    return NextResponse.json(
      { error: "Failed to seed properties" },
      { status: 500 }
    );
  }
}
